language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-16

env:
  global:
    ADB_INSTALL_TIMEOUT=6

before_script:
  - script/run_emulator

script:
  - ./gradlew test

after_script:
  - adb logcat -d
  - cat app/build/reports/lint-results.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack: userfeeds:AsvcCusl8zszBQXwkToCYZzY
